### PR TITLE
Wrapping, remove refresh, fix elements, and more.

### PR DESCRIPTION
**Pull request by maykar**
* Add wrapping from last tab to first tab and vice versa.
* Navigate only if swipe is long enough.
* Remove page refresh.
* Fix tab & container elements (moved in HA update).
* Remove up and down conditions.
* Clean, comment, and lint.

### CODE REVIEW

**Comment by klejejs** [comment]
Great work! This is much better than previous version.

When I tried the code I noticed that  I needed to add `.shadowRoot` also before `.querySelector("ha-panel-lovelace")` for the code to work.

The 3-5 second wait is a bit annoying, but that is only a small issue.

**Comment by maykar** [comment]
Just added a fix for older versions of HA where ha-panel-lovelace is contained within a shadowroot.

**Comment by themoffatt** [comment]
Thank you @maykar for submitting this! I had honestly forgotten about this project, and it didn't seem like it got much traction when I originally started it.  If you're ready for this to be merged, let me know and I'll merge it in.

**Comment by maykar** [comment]
Since adding this pull request I've done a rewrite and with themoffatt's  permission have created a new project for the rewrite. For now it is separate from compact-custom-header, but will most likely be added as a feature to CCH.

https://github.com/maykar/lovelace-swipe-navigation

Thanks again, @themoffatt !

**Pull request closed without merging**
